Watching for file changes with StatReloader
Watching for file changes with StatReloader
"OPTIONS /api/auth/register/ HTTP/1.1" 200 0
Bad Request: /api/auth/register/
"POST /api/auth/register/ HTTP/1.1" 400 52
Bad Request: /api/auth/register/
"POST /api/auth/register/ HTTP/1.1" 400 52
Bad Request: /api/auth/register/
"POST /api/auth/register/ HTTP/1.1" 400 52
Bad Request: /api/auth/register/
"POST /api/auth/register/ HTTP/1.1" 400 52
Failed to send OTP email to einsteinmofkua100@gmail.com: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-3b79c4533f1sm18330521f8f.42 - gsmtp')
Internal Server Error: /api/auth/register/
"POST /api/auth/register/ HTTP/1.1" 500 64
Watching for file changes with StatReloader
"POST /api/auth/register/ HTTP/1.1" 201 149
"OPTIONS /api/auth/verify-otp/ HTTP/1.1" 200 0
"POST /api/auth/verify-otp/ HTTP/1.1" 200 936
"OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
"GET /api/auth/profile/ HTTP/1.1" 200 393
"OPTIONS /api/auth/logout/ HTTP/1.1" 200 0
Bad Request: /api/auth/logout/
"POST /api/auth/logout/ HTTP/1.1" 400 26
/home/x/X/robolearn_backend/apps/authentication/views.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/authentication/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/authentication/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/authentication/utils.py changed, reloading.
Watching for file changes with StatReloader
Session data corrupted
"GET /admin/authentication/otpverification/ HTTP/1.1" 302 0
Session data corrupted
"GET /admin/login/?next=/admin/authentication/otpverification/ HTTP/1.1" 200 4240
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/css/login.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
Session data corrupted
"POST /admin/login/?next=/admin/authentication/otpverification/ HTTP/1.1" 302 0
"GET /admin/authentication/otpverification/ HTTP/1.1" 200 13081
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"OPTIONS /api/auth/login/ HTTP/1.1" 200 0
Bad Request: /api/auth/login/
"POST /api/auth/login/ HTTP/1.1" 400 51
Bad Request: /api/auth/login/
"POST /api/auth/login/ HTTP/1.1" 400 51
Bad Request: /api/auth/login/
"POST /api/auth/login/ HTTP/1.1" 400 51
"OPTIONS /api/auth/forgot-password/ HTTP/1.1" 200 0
"POST /api/auth/forgot-password/ HTTP/1.1" 200 88
"GET /admin/authentication/otpverification/ HTTP/1.1" 200 13730
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
/home/x/X/robolearn_backend/config/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/config/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/students/utils.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/students/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/authentication/otpverification/ HTTP/1.1" 200 16128
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
Bad Request: /api/auth/login/
"POST /api/auth/login/ HTTP/1.1" 400 51
"POST /api/auth/login/ HTTP/1.1" 200 925
"GET /api/auth/profile/ HTTP/1.1" 200 393
"GET /api/auth/profile/ HTTP/1.1" 200 393
"OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
Unauthorized: /api/auth/profile/
"GET /api/auth/profile/ HTTP/1.1" 401 183
"GET /admin/auth/ HTTP/1.1" 200 5193
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /admin/authentication/otpverification/ HTTP/1.1" 200 16128
"OPTIONS /api/students/dashboard/ HTTP/1.1" 200 0
Unauthorized: /api/students/dashboard/
"GET /api/students/dashboard/ HTTP/1.1" 401 58
Unauthorized: /api/students/dashboard/
"GET /api/students/dashboard/ HTTP/1.1" 401 58
Watching for file changes with StatReloader
"OPTIONS /api/auth/login/ HTTP/1.1" 200 0
Bad Request: /api/auth/login/
"POST /api/auth/login/ HTTP/1.1" 400 51
"POST /api/auth/login/ HTTP/1.1" 200 925
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"OPTIONS /api/students/my-courses/ HTTP/1.1" 200 0
"OPTIONS /api/students/courses/ HTTP/1.1" 200 0
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/courses/ HTTP/1.1" 200 52
"GET /api/auth/profile/ HTTP/1.1" 200 393
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/auth/profile/ HTTP/1.1" 200 393
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"GET /admin/authentication/otpverification/ HTTP/1.1" 200 16128
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
/home/x/X/robolearn_backend/apps/authentication/models.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/authentication/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/authentication/views.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/authentication/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/students/my-courses/
Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: users.first_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: users.first_name
Internal Server Error: /api/students/dashboard/
Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: users.first_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: users.first_name
"GET /api/students/my-courses/ HTTP/1.1" 500 204307
"GET /api/students/dashboard/ HTTP/1.1" 500 204289
Internal Server Error: /api/students/dashboard/
Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: users.first_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: users.first_name
"GET /api/students/dashboard/ HTTP/1.1" 500 204289
Internal Server Error: /api/students/my-courses/
Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: users.first_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: users.first_name
Internal Server Error: /api/students/dashboard/
Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: users.first_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: users.first_name
"GET /api/students/my-courses/ HTTP/1.1" 500 204307
"GET /api/students/dashboard/ HTTP/1.1" 500 204289
Internal Server Error: /api/auth/profile/
Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: users.first_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: users.first_name
"GET /api/auth/profile/ HTTP/1.1" 500 204219
Watching for file changes with StatReloader
"GET /api/auth/profile/ HTTP/1.1" 200 789
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/auth/profile/ HTTP/1.1" 200 789
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"GET /admin/authentication/otpverification/ HTTP/1.1" 200 16128
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
/home/x/X/robolearn_backend/apps/authentication/admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/authentication/otpverification/ HTTP/1.1" 200 15920
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/authentication/otpverification/ HTTP/1.1" 200 15920
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/ HTTP/1.1" 200 10592
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
Internal Server Error: /admin/authentication/user/
Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'profile_completion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: User has no field named 'profile_completion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 281, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/home/x/X/robolearn_backend/apps/authentication/admin.py", line 130, in profile_completion
    return format_html(
           ^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/utils/html.py", line 105, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'SafeString'
"GET /admin/authentication/user/ HTTP/1.1" 500 401773
/home/x/X/robolearn_backend/apps/authentication/admin.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/authentication/user/
Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'profile_completion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: User has no field named 'profile_completion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 281, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/home/x/X/robolearn_backend/apps/authentication/admin.py", line 130, in profile_completion
    return format_html(
           ^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/utils/html.py", line 105, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'SafeString'
"GET /admin/authentication/user/ HTTP/1.1" 500 401910
Internal Server Error: /admin/authentication/user/
Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'profile_completion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: User has no field named 'profile_completion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 281, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/home/x/X/robolearn_backend/apps/authentication/admin.py", line 130, in profile_completion
    return format_html(
           ^^^^^^^^^^^^
  File "/home/x/X/robolearn_backend/venv/lib/python3.12/site-packages/django/utils/html.py", line 105, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'SafeString'
"GET /admin/authentication/user/ HTTP/1.1" 500 401910
/home/x/X/robolearn_backend/apps/authentication/admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/authentication/user/ HTTP/1.1" 200 16218
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/authentication/user/3/change/ HTTP/1.1" 200 32527
"GET /static/admin/js/collapse.js HTTP/1.1" 200 1803
"GET /static/admin/css/forms.css HTTP/1.1" 200 9047
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11900
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15292
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
/home/x/X/robolearn_backend/apps/authentication/admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/authentication/user/ HTTP/1.1" 200 16218
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/authentication/user/3/change/ HTTP/1.1" 200 46605
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /api/auth/profile/ HTTP/1.1" 200 789
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/auth/profile/ HTTP/1.1" 200 789
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"GET /api/auth/profile/ HTTP/1.1" 200 789
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"GET /api/auth/profile/ HTTP/1.1" 200 789
"OPTIONS /api/auth/profile/update/ HTTP/1.1" 200 0
Bad Request: /api/auth/profile/update/
"PUT /api/auth/profile/update/ HTTP/1.1" 400 36
Bad Request: /api/auth/profile/update/
"PUT /api/auth/profile/update/ HTTP/1.1" 400 36
Bad Request: /api/auth/profile/update/
"PUT /api/auth/profile/update/ HTTP/1.1" 400 36
Bad Request: /api/auth/profile/update/
"PUT /api/auth/profile/update/ HTTP/1.1" 400 36
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/auth/profile/ HTTP/1.1" 200 789
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"GET /api/auth/profile/ HTTP/1.1" 200 789
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"GET /api/auth/profile/ HTTP/1.1" 200 789
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"GET /api/auth/profile/ HTTP/1.1" 200 789
Bad Request: /api/auth/profile/update/
"PUT /api/auth/profile/update/ HTTP/1.1" 400 36
"OPTIONS /api/students/my-courses/ HTTP/1.1" 200 0
"OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
"OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
"OPTIONS /api/students/dashboard/ HTTP/1.1" 200 0
Unauthorized: /api/students/my-courses/
Unauthorized: /api/auth/profile/
"GET /api/students/my-courses/ HTTP/1.1" 401 183
Unauthorized: /api/students/dashboard/
"GET /api/auth/profile/ HTTP/1.1" 401 183
"GET /api/students/dashboard/ HTTP/1.1" 401 183
Unauthorized: /api/auth/profile/
"GET /api/auth/profile/ HTTP/1.1" 401 183
Unauthorized: /api/students/my-courses/
Unauthorized: /api/auth/profile/
Unauthorized: /api/students/dashboard/
"GET /api/auth/profile/ HTTP/1.1" 401 58
"GET /api/students/dashboard/ HTTP/1.1" 401 58
"GET /api/students/my-courses/ HTTP/1.1" 401 58
Watching for file changes with StatReloader
"OPTIONS /api/auth/login/ HTTP/1.1" 200 0
"POST /api/auth/login/ HTTP/1.1" 200 933
"OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
"GET /api/auth/profile/ HTTP/1.1" 200 797
Watching for file changes with StatReloader
"GET /api/auth/profile/ HTTP/1.1" 200 797
"GET /api/auth/profile/ HTTP/1.1" 200 797
"OPTIONS /api/students/dashboard/ HTTP/1.1" 200 0
Forbidden: /api/students/dashboard/
"GET /api/students/dashboard/ HTTP/1.1" 403 50
"GET /api/auth/profile/ HTTP/1.1" 200 797
Forbidden: /api/students/dashboard/
"GET /api/students/dashboard/ HTTP/1.1" 403 50
"GET /api/auth/profile/ HTTP/1.1" 200 797
Forbidden: /api/students/dashboard/
"GET /api/students/dashboard/ HTTP/1.1" 403 50
"GET /api/auth/profile/ HTTP/1.1" 200 797
"GET /api/auth/profile/ HTTP/1.1" 200 797
"GET /api/auth/profile/ HTTP/1.1" 200 797
"GET /api/auth/profile/ HTTP/1.1" 200 797
"POST /api/auth/login/ HTTP/1.1" 200 925
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"OPTIONS /api/students/my-courses/ HTTP/1.1" 200 0
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/auth/profile/ HTTP/1.1" 200 789
"GET /api/students/dashboard/ HTTP/1.1" 200 572
"OPTIONS /api/auth/profile/avatar/ HTTP/1.1" 200 0
"POST /api/auth/profile/avatar/ HTTP/1.1" 200 115
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/dashboard/ HTTP/1.1" 200 561
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/students/dashboard/ HTTP/1.1" 200 561
"POST /api/auth/profile/avatar/ HTTP/1.1" 200 115
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/students/dashboard/ HTTP/1.1" 200 561
"OPTIONS /api/auth/profile/update/ HTTP/1.1" 200 0
Bad Request: /api/auth/profile/update/
"PUT /api/auth/profile/update/ HTTP/1.1" 400 36
Bad Request: /api/auth/profile/update/
"PUT /api/auth/profile/update/ HTTP/1.1" 400 36
Bad Request: /api/auth/profile/update/
"PUT /api/auth/profile/update/ HTTP/1.1" 400 36
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/dashboard/ HTTP/1.1" 200 561
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/dashboard/ HTTP/1.1" 200 561
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/dashboard/ HTTP/1.1" 200 561
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/dashboard/ HTTP/1.1" 200 561
"GET /api/auth/profile/ HTTP/1.1" 200 786
"GET /api/students/my-courses/ HTTP/1.1" 200 2
"GET /api/students/dashboard/ HTTP/1.1" 200 561
"GET /api/auth/profile/ HTTP/1.1" 200 786
/home/x/X/robolearn_backend/apps/authentication/models.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/authentication/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/authentication/views.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/apps/authentication/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/x/X/robolearn_backend/config/settings.py changed, reloading.
INFO 2025-08-05 18:20:58,725 autoreload 78527 125589247840384 Watching for file changes with StatReloader
INFO 2025-08-05 18:22:04,997 basehttp 78527 125589174343360 "GET /api/auth/profile/ HTTP/1.1" 200 841
INFO 2025-08-05 18:22:04,998 basehttp 78527 125589182736064 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-05 18:22:05,078 basehttp 78527 125589191128768 "GET /api/students/dashboard/ HTTP/1.1" 200 573
INFO 2025-08-05 18:22:05,488 basehttp 78527 125589165950656 "GET /api/auth/profile/ HTTP/1.1" 200 841
INFO 2025-08-05 18:22:16,145 views 78527 125589165950656 Avatar upload request from user 3
INFO 2025-08-05 18:22:16,308 views 78527 125589165950656 Avatar uploaded successfully for user 3
INFO 2025-08-05 18:22:16,310 basehttp 78527 125589165950656 "POST /api/auth/profile/avatar/ HTTP/1.1" 200 102
INFO 2025-08-05 18:22:16,363 basehttp 78527 125589165950656 "GET /api/auth/profile/ HTTP/1.1" 200 815
INFO 2025-08-05 18:22:20,203 views 78527 125589165950656 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '', 'location': '', 'date_of_birth': None, 'institution': '', 'major': '', 'year_of_study': '', 'bio': '', 'interests': [], 'learning_goals': '', 'github_profile': '', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
ERROR 2025-08-05 18:22:20,206 views 78527 125589165950656 Profile update validation errors for user 3: {'name': [ErrorDetail(string='This field is required.', code='required')]}
WARNING 2025-08-05 18:22:20,207 log 78527 125589165950656 Bad Request: /api/auth/profile/update/
WARNING 2025-08-05 18:22:20,216 basehttp 78527 125589165950656 "PUT /api/auth/profile/update/ HTTP/1.1" 400 36
INFO 2025-08-05 18:22:25,872 basehttp 78527 125589182736064 "GET /api/auth/profile/ HTTP/1.1" 200 815
INFO 2025-08-05 18:22:25,919 basehttp 78527 125589191128768 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-05 18:22:25,975 basehttp 78527 125589165950656 "GET /api/students/dashboard/ HTTP/1.1" 200 547
INFO 2025-08-05 18:22:26,331 basehttp 78527 125589174343360 "GET /api/auth/profile/ HTTP/1.1" 200 815
INFO 2025-08-05 18:23:52,180 views 78527 125589174343360 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboyah', 'phone': '', 'location': '', 'date_of_birth': None, 'institution': '', 'major': '', 'year_of_study': '', 'bio': '', 'interests': [], 'learning_goals': '', 'github_profile': '', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
ERROR 2025-08-05 18:23:52,204 views 78527 125589174343360 Profile update validation errors for user 3: {'name': [ErrorDetail(string='This field is required.', code='required')]}
WARNING 2025-08-05 18:23:52,220 log 78527 125589174343360 Bad Request: /api/auth/profile/update/
WARNING 2025-08-05 18:23:52,221 basehttp 78527 125589174343360 "PUT /api/auth/profile/update/ HTTP/1.1" 400 36
INFO 2025-08-05 18:35:52,433 autoreload 80959 136557742878848 Watching for file changes with StatReloader
INFO 2025-08-05 18:36:00,152 basehttp 80959 136557595973312 "GET /api/auth/profile/ HTTP/1.1" 200 815
INFO 2025-08-05 18:36:00,200 basehttp 80959 136557612758720 "GET /api/students/dashboard/ HTTP/1.1" 200 547
INFO 2025-08-05 18:36:00,218 basehttp 80959 136557604366016 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-05 18:36:00,567 basehttp 80959 136557595973312 "GET /api/auth/profile/ HTTP/1.1" 200 815
INFO 2025-08-05 18:36:28,568 views 80959 136557595973312 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': '', 'date_of_birth': None, 'institution': '', 'major': '', 'year_of_study': '', 'bio': '', 'interests': [], 'learning_goals': '', 'github_profile': '', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
INFO 2025-08-05 18:36:28,618 views 80959 136557595973312 Profile updated successfully for user 3
INFO 2025-08-05 18:36:28,622 basehttp 80959 136557595973312 "PUT /api/auth/profile/update/ HTTP/1.1" 200 876
INFO 2025-08-05 18:36:28,763 basehttp 80959 136557595973312 "GET /api/auth/profile/ HTTP/1.1" 200 825
INFO 2025-08-05 18:36:35,885 basehttp 80959 136557612758720 "GET /api/auth/profile/ HTTP/1.1" 200 825
INFO 2025-08-05 18:36:35,979 basehttp 80959 136557604366016 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-05 18:36:36,007 basehttp 80959 136557595973312 "GET /api/students/dashboard/ HTTP/1.1" 200 547
INFO 2025-08-05 18:36:36,138 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 825
INFO 2025-08-05 18:37:19,881 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': '', 'major': '', 'year_of_study': '', 'bio': '', 'interests': [], 'learning_goals': '', 'github_profile': '', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
INFO 2025-08-05 18:37:19,922 views 80959 136557587580608 Profile updated successfully for user 3
INFO 2025-08-05 18:37:20,176 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 200 883
INFO 2025-08-05 18:37:20,246 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 832
INFO 2025-08-05 18:37:26,423 basehttp 80959 136557604366016 "GET /api/auth/profile/ HTTP/1.1" 200 832
INFO 2025-08-05 18:37:26,413 basehttp 80959 136557595973312 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-05 18:37:26,595 basehttp 80959 136557612758720 "GET /api/auth/profile/ HTTP/1.1" 200 832
INFO 2025-08-05 18:37:26,601 basehttp 80959 136557587580608 "GET /api/students/dashboard/ HTTP/1.1" 200 547
INFO 2025-08-05 18:37:39,097 views 80959 136557587580608 Avatar upload request from user 3
INFO 2025-08-05 18:37:39,261 views 80959 136557587580608 Avatar uploaded successfully for user 3
INFO 2025-08-05 18:37:39,263 basehttp 80959 136557587580608 "POST /api/auth/profile/avatar/ HTTP/1.1" 200 102
INFO 2025-08-05 18:37:39,295 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 832
INFO 2025-08-05 18:37:45,680 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': '', 'major': '', 'year_of_study': '', 'bio': '', 'interests': [], 'learning_goals': '', 'github_profile': '', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
INFO 2025-08-05 18:37:45,699 views 80959 136557587580608 Profile updated successfully for user 3
INFO 2025-08-05 18:37:45,702 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 200 883
INFO 2025-08-05 18:37:45,785 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 832
INFO 2025-08-05 18:37:49,800 basehttp 80959 136557595973312 "GET /api/auth/profile/ HTTP/1.1" 200 832
INFO 2025-08-05 18:37:49,854 basehttp 80959 136557612758720 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-05 18:37:50,027 basehttp 80959 136557587580608 "GET /api/students/dashboard/ HTTP/1.1" 200 547
INFO 2025-08-05 18:37:50,041 basehttp 80959 136557604366016 "GET /api/auth/profile/ HTTP/1.1" 200 832
WARNING 2025-08-05 19:09:24,447 log 80959 136557612758720 Unauthorized: /api/students/my-courses/
WARNING 2025-08-05 19:09:24,452 log 80959 136557587580608 Unauthorized: /api/students/dashboard/
WARNING 2025-08-05 19:09:24,441 log 80959 136557595973312 Unauthorized: /api/auth/profile/
WARNING 2025-08-05 19:09:24,536 basehttp 80959 136557587580608 "GET /api/students/dashboard/ HTTP/1.1" 401 183
WARNING 2025-08-05 19:09:24,551 basehttp 80959 136557595973312 "GET /api/auth/profile/ HTTP/1.1" 401 183
WARNING 2025-08-05 19:09:24,647 basehttp 80959 136557612758720 "GET /api/students/my-courses/ HTTP/1.1" 401 183
WARNING 2025-08-05 19:09:24,677 log 80959 136557612758720 Unauthorized: /api/auth/profile/
WARNING 2025-08-05 19:09:24,681 basehttp 80959 136557612758720 "GET /api/auth/profile/ HTTP/1.1" 401 183
INFO 2025-08-05 19:10:14,862 basehttp 80959 136557612758720 "POST /api/auth/login/ HTTP/1.1" 200 900
INFO 2025-08-05 19:10:15,140 basehttp 80959 136557612758720 "GET /api/students/dashboard/ HTTP/1.1" 200 547
INFO 2025-08-05 19:10:22,729 basehttp 80959 136557612758720 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-05 19:10:22,778 basehttp 80959 136557595973312 "GET /api/auth/profile/ HTTP/1.1" 200 832
INFO 2025-08-05 19:10:22,854 basehttp 80959 136557587580608 "GET /api/students/dashboard/ HTTP/1.1" 200 547
INFO 2025-08-05 19:10:40,059 views 80959 136557587580608 Avatar upload request from user 3
INFO 2025-08-05 19:10:40,182 views 80959 136557587580608 Avatar uploaded successfully for user 3
INFO 2025-08-05 19:10:40,186 basehttp 80959 136557587580608 "POST /api/auth/profile/avatar/ HTTP/1.1" 200 101
INFO 2025-08-05 19:10:40,282 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 831
INFO 2025-08-05 19:11:28,974 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': '', 'major': '', 'year_of_study': '', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': '', 'github_profile': 'https://nyandieka-portfolio.vercel.app/', 'linkedin_profile': 'linkedin.com/nyandiekahh', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
ERROR 2025-08-05 19:11:29,302 views 80959 136557587580608 Profile update validation errors for user 3: {'github_profile': [ErrorDetail(string='Please enter a valid GitHub profile URL.', code='invalid')], 'linkedin_profile': [ErrorDetail(string='Enter a valid URL.', code='invalid')]}
WARNING 2025-08-05 19:11:29,311 log 80959 136557587580608 Bad Request: /api/auth/profile/update/
WARNING 2025-08-05 19:11:29,312 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 400 105
INFO 2025-08-05 19:12:03,185 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': '', 'major': '', 'year_of_study': '', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': '', 'github_profile': 'https://nyandieka-portfolio.vercel.app/', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
ERROR 2025-08-05 19:12:03,200 views 80959 136557587580608 Profile update validation errors for user 3: {'github_profile': [ErrorDetail(string='Please enter a valid GitHub profile URL.', code='invalid')]}
WARNING 2025-08-05 19:12:03,202 log 80959 136557587580608 Bad Request: /api/auth/profile/update/
WARNING 2025-08-05 19:12:03,221 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 400 63
INFO 2025-08-05 19:12:40,823 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': '', 'major': '', 'year_of_study': '', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': '', 'github_profile': 'github.com/Nyandiekahh', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
ERROR 2025-08-05 19:12:40,832 views 80959 136557587580608 Profile update validation errors for user 3: {'github_profile': [ErrorDetail(string='Enter a valid URL.', code='invalid')]}
WARNING 2025-08-05 19:12:40,842 log 80959 136557587580608 Bad Request: /api/auth/profile/update/
WARNING 2025-08-05 19:12:40,845 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 400 41
INFO 2025-08-05 19:13:09,243 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': '', 'major': '', 'year_of_study': '', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': '', 'github_profile': '', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
INFO 2025-08-05 19:13:09,482 views 80959 136557587580608 Profile updated successfully for user 3
INFO 2025-08-05 19:13:09,486 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 200 910
INFO 2025-08-05 19:13:09,604 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 859
INFO 2025-08-05 19:13:23,040 views 80959 136557587580608 Avatar upload request from user 3
INFO 2025-08-05 19:13:23,234 views 80959 136557587580608 Avatar uploaded successfully for user 3
INFO 2025-08-05 19:13:23,238 basehttp 80959 136557587580608 "POST /api/auth/profile/avatar/ HTTP/1.1" 200 92
INFO 2025-08-05 19:13:23,435 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 850
INFO 2025-08-05 19:13:26,246 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': '', 'major': '', 'year_of_study': '', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': '', 'github_profile': '', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
INFO 2025-08-05 19:13:26,435 views 80959 136557587580608 Profile updated successfully for user 3
INFO 2025-08-05 19:13:26,438 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 200 901
INFO 2025-08-05 19:13:26,495 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 850
INFO 2025-08-05 19:13:34,876 basehttp 80959 136557612758720 "GET /api/auth/profile/ HTTP/1.1" 200 850
INFO 2025-08-05 19:13:35,140 basehttp 80959 136557595973312 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-05 19:13:35,330 basehttp 80959 136557587580608 "GET /api/students/dashboard/ HTTP/1.1" 200 537
INFO 2025-08-05 19:14:10,193 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': 'JKUAT', 'major': 'Mechatronics', 'year_of_study': 'freshman', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': 'No Goals set yet', 'github_profile': '', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
INFO 2025-08-05 19:14:10,227 views 80959 136557587580608 Profile updated successfully for user 3
INFO 2025-08-05 19:14:10,232 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 200 942
INFO 2025-08-05 19:14:10,284 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 891
INFO 2025-08-06 02:49:20,273 basehttp 80959 136557595973312 "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
WARNING 2025-08-06 02:49:20,447 log 80959 136557595973312 Unauthorized: /api/auth/profile/
WARNING 2025-08-06 02:49:20,447 basehttp 80959 136557595973312 "GET /api/auth/profile/ HTTP/1.1" 401 183
INFO 2025-08-06 02:56:22,709 basehttp 80959 136557595973312 "OPTIONS /api/auth/login/ HTTP/1.1" 200 0
INFO 2025-08-06 02:56:23,499 basehttp 80959 136557595973312 "POST /api/auth/login/ HTTP/1.1" 200 890
INFO 2025-08-06 02:56:23,612 basehttp 80959 136557595973312 "OPTIONS /api/students/dashboard/ HTTP/1.1" 200 0
INFO 2025-08-06 02:56:23,797 basehttp 80959 136557595973312 "GET /api/students/dashboard/ HTTP/1.1" 200 537
INFO 2025-08-06 02:56:25,769 basehttp 80959 136557595973312 "OPTIONS /api/students/my-courses/ HTTP/1.1" 200 0
INFO 2025-08-06 02:56:25,838 basehttp 80959 136557595973312 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-06 02:56:25,869 basehttp 80959 136557612758720 "OPTIONS /api/students/courses/ HTTP/1.1" 200 0
INFO 2025-08-06 02:56:25,968 basehttp 80959 136557612758720 "GET /api/students/courses/ HTTP/1.1" 200 52
INFO 2025-08-06 02:56:59,045 basehttp 80959 136557612758720 "GET /api/students/dashboard/ HTTP/1.1" 200 537
INFO 2025-08-06 02:57:15,960 basehttp 80959 136557595973312 "GET /api/auth/profile/ HTTP/1.1" 200 891
INFO 2025-08-06 02:57:16,015 basehttp 80959 136557612758720 "GET /api/students/dashboard/ HTTP/1.1" 200 537
INFO 2025-08-06 02:57:16,135 basehttp 80959 136557587580608 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-06 02:58:38,661 basehttp 80959 136557587580608 "OPTIONS /api/auth/profile/update/ HTTP/1.1" 200 0
INFO 2025-08-06 02:58:38,700 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': 'JKUAT', 'major': 'Mechatronics', 'year_of_study': 'freshman', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': 'No Goals set yet', 'github_profile': 'https://github.com/Nyandiekahh', 'linkedin_profile': '', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
INFO 2025-08-06 02:58:38,777 views 80959 136557587580608 Profile updated successfully for user 3
INFO 2025-08-06 02:58:38,779 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 200 972
INFO 2025-08-06 02:58:38,848 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 921
INFO 2025-08-06 02:58:55,154 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': 'JKUAT', 'major': 'Mechatronics', 'year_of_study': 'freshman', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': 'No Goals set yet', 'github_profile': 'https://github.com/Nyandiekahh', 'linkedin_profile': 'linkedin/nyandiekahh', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
ERROR 2025-08-06 02:58:55,181 views 80959 136557587580608 Profile update validation errors for user 3: {'linkedin_profile': [ErrorDetail(string='Enter a valid URL.', code='invalid')]}
WARNING 2025-08-06 02:58:55,184 log 80959 136557587580608 Bad Request: /api/auth/profile/update/
WARNING 2025-08-06 02:58:55,185 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 400 43
INFO 2025-08-06 03:02:08,421 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': 'JKUAT', 'major': 'Mechatronics', 'year_of_study': 'freshman', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': 'No Goals set yet', 'github_profile': 'https://github.com/Nyandiekahh', 'linkedin_profile': 'https://www.linkedin.com/in/leah-mathenge-96a8152b1/', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
INFO 2025-08-06 03:02:08,469 views 80959 136557587580608 Profile updated successfully for user 3
INFO 2025-08-06 03:02:08,497 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 200 1024
INFO 2025-08-06 03:02:08,557 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 973
INFO 2025-08-06 03:02:23,441 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': 'JKUAT', 'major': 'Mechatronics', 'year_of_study': 'freshman', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': 'No Goals set yet', 'github_profile': 'https://github.com/Nyandiekahh', 'linkedin_profile': 'www.linkedin.com/in/einstein-mokua-b9886b220', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
ERROR 2025-08-06 03:02:23,445 views 80959 136557587580608 Profile update validation errors for user 3: {'linkedin_profile': [ErrorDetail(string='Enter a valid URL.', code='invalid')]}
WARNING 2025-08-06 03:02:23,446 log 80959 136557587580608 Bad Request: /api/auth/profile/update/
WARNING 2025-08-06 03:02:23,447 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 400 43
INFO 2025-08-06 03:02:32,749 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': 'JKUAT', 'major': 'Mechatronics', 'year_of_study': 'freshman', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': 'No Goals set yet', 'github_profile': 'https://github.com/Nyandiekahh', 'linkedin_profile': 'www.linkedin.com/in/einstein-mokua-b9886b220', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
ERROR 2025-08-06 03:02:32,754 views 80959 136557587580608 Profile update validation errors for user 3: {'linkedin_profile': [ErrorDetail(string='Enter a valid URL.', code='invalid')]}
WARNING 2025-08-06 03:02:32,755 log 80959 136557587580608 Bad Request: /api/auth/profile/update/
WARNING 2025-08-06 03:02:32,755 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 400 43
INFO 2025-08-06 03:02:53,804 views 80959 136557587580608 Profile update request from user 3: {'first_name': 'Tom', 'last_name': 'Mboya', 'phone': '0719408098', 'location': 'Kajiado', 'date_of_birth': None, 'institution': 'JKUAT', 'major': 'Mechatronics', 'year_of_study': 'freshman', 'bio': 'The Bio definitely goes here', 'interests': [], 'learning_goals': 'No Goals set yet', 'github_profile': 'https://github.com/Nyandiekahh', 'linkedin_profile': 'https://linkedin.com/in/einstein-mokua-b9886b220', 'email_notifications': True, 'push_notifications': False, 'weekly_progress': True, 'course_updates': True, 'marketing': False, 'public_profile': False, 'show_progress': True, 'show_achievements': True}
INFO 2025-08-06 03:02:53,826 views 80959 136557587580608 Profile updated successfully for user 3
INFO 2025-08-06 03:02:53,829 basehttp 80959 136557587580608 "PUT /api/auth/profile/update/ HTTP/1.1" 200 1020
INFO 2025-08-06 03:02:53,852 basehttp 80959 136557587580608 "GET /api/auth/profile/ HTTP/1.1" 200 969
INFO 2025-08-06 03:03:44,900 basehttp 80959 136557587580608 "GET /api/students/dashboard/ HTTP/1.1" 200 537
INFO 2025-08-06 07:39:55,562 basehttp 80959 136557587580608 "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
INFO 2025-08-06 07:39:55,557 basehttp 80959 136557612758720 "OPTIONS /api/students/dashboard/ HTTP/1.1" 200 0
WARNING 2025-08-06 07:39:55,751 log 80959 136557612758720 Unauthorized: /api/auth/profile/
WARNING 2025-08-06 07:39:55,752 log 80959 136557587580608 Unauthorized: /api/students/dashboard/
WARNING 2025-08-06 07:39:55,754 basehttp 80959 136557612758720 "GET /api/auth/profile/ HTTP/1.1" 401 183
WARNING 2025-08-06 07:39:55,755 basehttp 80959 136557587580608 "GET /api/students/dashboard/ HTTP/1.1" 401 183
WARNING 2025-08-06 07:43:53,742 log 80959 136557587580608 Unauthorized: /api/students/dashboard/
WARNING 2025-08-06 07:43:53,745 basehttp 80959 136557587580608 "GET /api/students/dashboard/ HTTP/1.1" 401 58
INFO 2025-08-06 07:44:30,152 basehttp 80959 136557587580608 "OPTIONS /api/auth/login/ HTTP/1.1" 200 0
INFO 2025-08-06 07:44:30,849 basehttp 80959 136557587580608 "POST /api/auth/login/ HTTP/1.1" 200 890
INFO 2025-08-06 07:44:31,012 basehttp 80959 136557587580608 "GET /api/students/dashboard/ HTTP/1.1" 200 537
INFO 2025-08-06 07:45:00,161 basehttp 80959 136557612758720 "OPTIONS /api/students/my-courses/ HTTP/1.1" 200 0
INFO 2025-08-06 07:45:00,227 basehttp 80959 136557612758720 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-06 07:45:00,233 basehttp 80959 136557587580608 "GET /api/students/dashboard/ HTTP/1.1" 200 537
INFO 2025-08-06 07:45:00,250 basehttp 80959 136557595973312 "GET /api/auth/profile/ HTTP/1.1" 200 969
INFO 2025-08-06 07:45:34,938 basehttp 80959 136557612758720 "GET /api/students/dashboard/ HTTP/1.1" 200 537
INFO 2025-08-06 17:40:26,445 autoreload 134999 128184625651840 Watching for file changes with StatReloader
INFO 2025-08-06 17:41:04,071 autoreload 135355 127005708599424 Watching for file changes with StatReloader
INFO 2025-08-06 17:41:33,258 basehttp 135355 127005651629760 "OPTIONS /api/auth/login/ HTTP/1.1" 200 0
INFO 2025-08-06 17:41:34,259 basehttp 135355 127005651629760 "POST /api/auth/login/ HTTP/1.1" 200 890
INFO 2025-08-06 17:41:34,455 basehttp 135355 127005651629760 "OPTIONS /api/students/dashboard/ HTTP/1.1" 200 0
INFO 2025-08-06 17:41:34,556 basehttp 135355 127005651629760 "GET /api/students/dashboard/ HTTP/1.1" 200 537
INFO 2025-08-06 17:42:23,169 basehttp 135355 127005651629760 "OPTIONS /api/students/my-courses/ HTTP/1.1" 200 0
INFO 2025-08-06 17:42:23,216 basehttp 135355 127005642188480 "OPTIONS /api/auth/profile/ HTTP/1.1" 200 0
INFO 2025-08-06 17:42:23,337 basehttp 135355 127005651629760 "GET /api/students/my-courses/ HTTP/1.1" 200 2
INFO 2025-08-06 17:42:23,351 basehttp 135355 127005642188480 "GET /api/auth/profile/ HTTP/1.1" 200 969
INFO 2025-08-06 17:42:23,440 basehttp 135355 127005633795776 "GET /api/students/dashboard/ HTTP/1.1" 200 537
INFO 2025-08-06 17:42:35,102 basehttp 135355 127005633795776 "GET /api/students/dashboard/ HTTP/1.1" 200 537
